pub const TRANSFER_IXS_CHUNK_SIZE: usize = 18;
pub const ATA_GET_MULT_ACC_CHUNK_SIZE: usize = 100;

pub const CHECK_MAX_RETRY: usize = 4;

pub const DEFAULT_COMPUTE_UNIT_LIMIT: u32 = 1_000_000;
pub const DEFAULT_COMPUTE_UNIT_PRICE: u64 = 1;
pub const DEFAULT_SNAPSHOT_MINIMUM_BALANCE_ATOMIC: u64 = 1;
